substitutions:
  _IMAGE_NAME: lastversion
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: build
  args:
  - --destination=gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest
  - --cache=true
  - --cache-ttl=48h
  - --single-snapshot
  - --context=./
timeout: 3600s
options:
  dynamic_substitutions: true
