steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: build
  args:
  - --destination=gcr.io/$PROJECT_ID/IMAGE:latest
  - --cache=true
  - --cache-ttl=48h
  - --context=./
timeout: 3600s
substitutions:
  _IMAGE_NAME: test-image
options:
  dynamic_substitutions: true
